version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: my-adminer-container
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres-data: