
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    env_file: docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container
    depends_on:
      - postgres
    env_file: docker.env
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: